### ISSUE TITLE
Create a logo for the engine

### ISSUE THREAD

**Issue by amiller7023** [Jmiller7023/Xenro-Engine#11]
A simple yet elegant logo is needed for the engine to display before games utilizing the engine much like the splash screens for Unreal and Unity.

**Comment by mirzazulfan** [comment]
Hi @Jmiller7023 ,, i've designed a logo. What do you think? 
![xenro](https://user-images.githubusercontent.com/36124339/49284618-aba22680-f4c7-11e8-9c42-6d777852b087.png)

**Comment by amiller7023** [comment]
This looks amazing! Would it be possible to have the graphic at the top in blue with Xenro written below it?

**Comment by mirzazulfan** [comment]
Im glad you liked it, sure, I'll change it and send you all files immediately.

**Comment by mirzazulfan** [comment]
Hi @Jmiller7023 ,, I've created a pr #21 .. download all files [here](https://drive.google.com/drive/folders/1MEdK7HMGEYi2WApELVtVsvYpA4RAJCE5?ogsrc=32)
Best Regard.

**Comment by amiller7023** [comment]
Thank you very much. I have completed your pull request
